name: Homebrew Formula Test

on: [push]

jobs:
  test_formula:
    name: Test ${{ matrix.formula }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        formula: [ona]

    steps:
    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@55e35ac78132cc31ce174408f40a9676e64aa0e2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Tap and install formula
      run: |
        brew tap gitpod-io/tap ${{ github.server_url }}/${{ github.repository }} --force
        brew install gitpod-io/tap/${{ matrix.formula }}

    - name: Test formula
      run: brew test ${{ matrix.formula }}
